Repository gunmack/276_Project, pull requests merged in 2024-11, with the labels that each got.

#8 Landing page complete and hamburger tab mostly complete
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.js
  src/app/main-menu/page.js
  src/app/page.js
  tailwind.config.js
Labels: UI/UX

#24 made toolbar a seperate component and added dummy pages for all the features
  src/app/Toolbar.js
  src/app/achievements/page.js
  src/app/ai-conversations/page.js
  src/app/flashcards/page.js
  src/app/learn-vocab/page.js
  src/app/main-menu/page.js
  src/app/quizzes/page.js
  src/app/text-to-speech/page.js
Labels: UI/UX

#42 Fixed some UI issues and added Flashcards feature
  package-lock.json
  package.json
  pages/api/flashcardsTranslate.js
  pages/api/generateFlashcards.js
  src/app/Toolbar.js
  src/app/flashcards/page.js
  src/app/globals.css
  src/app/main-menu/page.js
  src/app/page.js
  test-reports/test-report.html
Labels: UI/UX, feature

#48 UI/UX updates
  pages/api/generateFlashcards.js
  src/app/ai-conversations/page.js
  src/app/flashcards/page.js
  src/app/globals.css
  src/app/learn-vocab/page.js
  src/app/quizzes/page.js
  src/app/text-to-speech/page.js
Labels: UI/UX

#52 more general UI updates, now including achievements
  components/TextToSpeechButton.js
  components/VocabBox.js
  package-lock.json
  package.json
  src/app/Toolbar.js
  src/app/achievements/page.js
  src/app/ai-conversations/page.js
  src/app/auth/page.js
  src/app/flashcards/page.js
  src/app/globals.css
  src/app/learn-vocab/page.js
  src/app/logout/page.js
  src/app/page.js
  src/app/quizzes/page.js
  src/app/text-to-speech/page.js
Labels: UI/UX

#62 UI/UX 4
  __tests__/pages.test.js
  src/app/achievements/page.js
  src/app/ai-conversations/page.js
  src/app/auth/page.js
  src/app/components/TextToSpeechButton.js
  src/app/components/Toolbar.js
  src/app/components/VocabBox.js
  src/app/flashcards/page.js
  src/app/globals.css
  src/app/learn-vocab/page.js
  src/app/logout/page.js
  src/app/main-menu/page.js
  src/app/page.js
  src/app/quizzes/page.js
  src/app/text-to-speech/page.js
Labels: UI/UX

#64 updated workflow
  .eslintrc.json
  .github/workflows/deploy.yml
  .github/workflows/pipeline.yml
  .gitignore
Labels: DevOps
